Implementation of LOOCV Ridge Regression method
atztogo/symfc-alm pull request #5
Opened 2023-07-18 08:53 UTC by narutak

Thank you for all the work @atztogo. I have implemented the computation of the force constants using Leave-One-Out Cross Validation (LOOCV) Ridge Regression to symfc-alm.

- Implementation of LOOCV Ridge Regression: I have implemented a RidgeRegression class, which you can find in src/symfc_alm/symfc_alm.py.
- Data standardization function: Additionally, within the same file, src/symfc_alm/symfc_alm.py, I have also incorporated a function for standardizing input data, which will aid in the performance of our Ridge Regression model.

In order to verify the functionality and reliability of the new implementations, I've written two sets of tests:
- RidgeRegression Class Tests: You can find the tests for the RidgeRegression class in tests/test_ridge.py.
- RidgeRegression Run Tests: I have also written tests to ensure that the RidgeRegression model runs smoothly. They are available in tests/test_symfc-alm.py.

Please feel free to review the changes and leave any feedback or comments. I look forward to your review of the pull request.

2023-07-23 04:19 UTC, atztogo requested changes

2023-07-23 04:19 UTC, atztogo commented on tests/test_ridge.py
> +def data(si_111_dataset: DispForceDataset, si_111_structure: CellDataset):
`si_111_dataset` is a full-rank dataset. So tests with another rank deficient data are expected.

2023-07-23 04:19 UTC, atztogo commented on tests/test_ridge.py
> +def regression():
Is this fixture necessary?

2023-07-23 04:19 UTC, atztogo commented on tests/test_ridge.py
> +def data(si_111_dataset: DispForceDataset, si_111_structure: CellDataset):
This fixture can be placed in `conftest.py` with a longer variable name than `data`.

2023-07-24 03:07 UTC, narutak commented on tests/test_ridge.py
> +def data(si_111_dataset: DispForceDataset, si_111_structure: CellDataset):
I have made the corrections as requested. Please review tests.

2023-07-24 03:07 UTC, narutak commented on tests/test_ridge.py
> +def regression():
I have removed it and fixed the code to create a RidgeRegression class for each function. Please review it.

2023-07-24 03:09 UTC, narutak commented
I've added the debias option to RidgeRegression._fit() of src/symfc_alm/ridge.py.

2023-07-24 03:09 UTC, atztogo commented on tests/test_ridge.py
> +def data(si_111_dataset: DispForceDataset, si_111_structure: CellDataset):
Thanks @narutak. Looks good.

2023-07-24 04:21 UTC, narutak commented
Please review the code and if there are no issues, I request you to merge it.

2023-07-24 04:45 UTC, atztogo approved these changes

2023-07-24 04:47 UTC, atztogo commented
Thanks @narutak. I merged manually excluding the commit adding `.vscode/settings.json`.

2023-07-24 04:47 UTC, closed without merging